version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_TCP_PORT: '3307'
      MYSQL_DATABASE: 'dbgnp_gnp'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3307'
    expose:
      # Opens port 3306 on the container
      - '3307'
      # Where our data will be persisted

    volumes:
      - my-db:/var/lib/mysql
       # ATTENTION HANUI
      - /home/u71:/backup
# Names our volume
volumes:
  my-db: